default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: billing_app_development
  username: <%= Rails.application.credentials.dig(:development, :username) %>
  username: <%= Rails.application.credentials.dig(:development, :password) %>

test:
  <<: *default
  database: billing_app_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
