default: &default
  adapter: postgresql
  encoding: utf8

development:
  <<: *default
  database: billing_app_development
  username: <%= Rails.application.credentials.dig(:development, :username) %>
  password: <%= Rails.application.credentials.dig(:development, :password) %>

test:
  <<: *default
  database: billing_app_test

production:
  primary: &primary_production
    <<: *default
    database: billing_app_production
    username: billing_app
    password: <%= ENV["BILLING_APP_DATABASE_PASSWORD"] %>
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *primary_production
    database: billing_app_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: billing_app_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: billing_app_production_cable
    migrations_paths: db/cable_migrate
